export interface PartProduct {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  originalPrice: number;
  image: string;
  inStock: boolean;
  stockCount: number;
  genuine: boolean;
  discount: number;
  compatibility: string;
  rating: number;
  reviews: number;
  make: string;
  model: string;
  year: string;
  specs?: string;
}

export const carMakes = [
  "Maruti",
  "Hyundai",
  "Tata",
  "Honda",
  "Mahindra",
  "Toyota",
  "Kia",
  "Skoda",
  "Renault",
  "Volkswagen",
];

export const models: Record<string, string[]> = {
  Maruti: ["Swift", "Alto", "Celerio", "Wagon R", "Baleno"],
  Hyundai: ["i10", "i20", "Creta", "Venue", "Verna"],
  Tata: ["Nexon", "Altroz", "Tiago", "Tigor", "Harrier"],
  Honda: ["City", "Jazz", "CR-V", "Amaze", "Accord"],
  Mahindra: ["XUV500", "XUV300", "Bolero", "TUV300", "Scorpio"],
  Toyota: ["Fortuner", "Innova", "Corolla", "Camry", "Glanza"],
  Kia: ["Seltos", "Sonet", "Carnival", "EV6", "Niro"],
  Skoda: ["Octavia", "Superb", "Slavia", "Rapid", "Karoq"],
  Renault: ["Kwid", "Duster", "Triber", "Kiger", "RXZ"],
  Volkswagen: ["Polo", "Vento", "Taigun", "Tiguan", "Virtus"],
};

export const categories = [
  "Engine Parts",
  "Brakes",
  "Electrical",
  "Filters",
  "Suspension",
  "Cooling",
  "Body Parts",
  "Clutch",
];

export const years = Array.from({ length: 20 }, (_, i) => String(2024 - i));

export const mockProducts: PartProduct[] = [
  {
    id: "1",
    name: "Engine Oil Filter Premium",
    brand: "Bosch",
    category: "Filters",
    price: 349,
    originalPrice: 499,
    image: "https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 45,
    genuine: true,
    discount: 15,
    compatibility: "Maruti Swift, Alto, Celerio",
    rating: 4.8,
    reviews: 234,
    make: "Maruti",
    model: "Swift",
    year: "2023",
  },
  {
    id: "2",
    name: "Air Intake Filter",
    brand: "Mann",
    category: "Filters",
    price: 299,
    originalPrice: 449,
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 62,
    genuine: true,
    discount: 20,
    compatibility: "Hyundai i20, Creta, Venue",
    rating: 4.7,
    reviews: 189,
    make: "Hyundai",
    model: "i20",
    year: "2024",
  },
  {
    id: "3",
    name: "Brake Pad Set",
    brand: "Brembo",
    category: "Brakes",
    price: 1299,
    originalPrice: 1799,
    image: "https://images.unsplash.com/photo-1516684657222-7d7d9c2eae5d?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 28,
    genuine: true,
    discount: 25,
    compatibility: "Tata Nexon, Altroz, Tiago",
    rating: 4.9,
    reviews: 456,
    make: "Tata",
    model: "Nexon",
    year: "2023",
  },
  {
    id: "4",
    name: "Spark Plugs Set",
    brand: "NGK",
    category: "Engine Parts",
    price: 599,
    originalPrice: 899,
    image: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 35,
    genuine: true,
    discount: 18,
    compatibility: "Honda City, Jazz, Amaze",
    rating: 4.6,
    reviews: 312,
    make: "Honda",
    model: "City",
    year: "2024",
  },
  {
    id: "5",
    name: "Battery 60Ah",
    brand: "Exide",
    category: "Electrical",
    price: 4200,
    originalPrice: 5500,
    image: "https://images.unsplash.com/photo-1581092934665-96e8bb648b0f?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 15,
    genuine: true,
    discount: 23,
    compatibility: "All Cars",
    rating: 4.7,
    reviews: 523,
    make: "Mahindra",
    model: "XUV500",
    year: "2023",
  },
  {
    id: "6",
    name: "Water Pump Assembly",
    brand: "Kirloskar",
    category: "Cooling",
    price: 2899,
    originalPrice: 3999,
    image: "https://images.unsplash.com/photo-1581092334473-e85ebef0edd4?w=400&h=400&fit=crop",
    inStock: false,
    stockCount: 0,
    genuine: true,
    discount: 27,
    compatibility: "Toyota Fortuner, Innova",
    rating: 4.5,
    reviews: 198,
    make: "Toyota",
    model: "Fortuner",
    year: "2022",
  },
  {
    id: "7",
    name: "Alternator",
    brand: "Bosch",
    category: "Electrical",
    price: 5999,
    originalPrice: 7999,
    image: "https://images.unsplash.com/photo-1581092891221-8022df4466f9?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 12,
    genuine: true,
    discount: 25,
    compatibility: "Maruti Alto, Wagon R",
    rating: 4.8,
    reviews: 267,
    make: "Maruti",
    model: "Alto",
    year: "2023",
  },
  {
    id: "8",
    name: "Suspension Spring",
    brand: "TRW",
    category: "Suspension",
    price: 1899,
    originalPrice: 2799,
    image: "https://images.unsplash.com/photo-1581092167562-40cb08bac841?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 42,
    genuine: true,
    discount: 20,
    compatibility: "Hyundai Creta, Venue",
    rating: 4.6,
    reviews: 234,
    make: "Hyundai",
    model: "Creta",
    year: "2024",
  },
  {
    id: "9",
    name: "Clutch Kit Assembly",
    brand: "Valeo",
    category: "Clutch",
    price: 3499,
    originalPrice: 4999,
    image: "https://images.unsplash.com/photo-1581092915550-12bec35d8f0c?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 18,
    genuine: true,
    discount: 22,
    compatibility: "Tata Altroz, Tiago",
    rating: 4.7,
    reviews: 189,
    make: "Tata",
    model: "Altroz",
    year: "2023",
  },
  {
    id: "10",
    name: "Air Conditioner Compressor",
    brand: "Sanden",
    category: "Cooling",
    price: 6999,
    originalPrice: 9999,
    image: "https://images.unsplash.com/photo-1581092162080-8cda6b69a133?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 8,
    genuine: true,
    discount: 30,
    compatibility: "Honda CR-V, Accord",
    rating: 4.9,
    reviews: 345,
    make: "Honda",
    model: "CR-V",
    year: "2024",
  },
  {
    id: "11",
    name: "Fuel Pump",
    brand: "Bosch",
    category: "Engine Parts",
    price: 4499,
    originalPrice: 6299,
    image: "https://images.unsplash.com/photo-1581092179564-1b5b35e7ec6c?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 22,
    genuine: true,
    discount: 28,
    compatibility: "Mahindra XUV300, Bolero",
    rating: 4.6,
    reviews: 178,
    make: "Mahindra",
    model: "XUV300",
    year: "2023",
  },
  {
    id: "12",
    name: "Starter Motor",
    brand: "Nippon Denso",
    category: "Electrical",
    price: 3299,
    originalPrice: 4799,
    image: "https://images.unsplash.com/photo-1581092160562-40cb08bac842?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 31,
    genuine: true,
    discount: 18,
    compatibility: "Toyota Glanza, Corolla",
    rating: 4.7,
    reviews: 212,
    make: "Toyota",
    model: "Glanza",
    year: "2024",
  },
  {
    id: "13",
    name: "Radiator",
    brand: "Modine",
    category: "Cooling",
    price: 2599,
    originalPrice: 3699,
    image: "https://images.unsplash.com/photo-1581092162080-8cda6b69a134?w=400&h=400&fit=crop",
    inStock: false,
    stockCount: 0,
    genuine: true,
    discount: 29,
    compatibility: "Kia Seltos, Sonet",
    rating: 4.5,
    reviews: 156,
    make: "Kia",
    model: "Seltos",
    year: "2023",
  },
  {
    id: "14",
    name: "Door Handle Assembly",
    brand: "OEM",
    category: "Body Parts",
    price: 799,
    originalPrice: 1199,
    image: "https://images.unsplash.com/photo-1581092334850-1c1d19e91fa7?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 56,
    genuine: true,
    discount: 12,
    compatibility: "Skoda Octavia, Superb",
    rating: 4.4,
    reviews: 89,
    make: "Skoda",
    model: "Octavia",
    year: "2022",
  },
  {
    id: "15",
    name: "Front Bumper",
    brand: "OEM",
    category: "Body Parts",
    price: 3499,
    originalPrice: 5199,
    image: "https://images.unsplash.com/photo-1581092333144-8d5e4b5e5e5f?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 5,
    genuine: true,
    discount: 17,
    compatibility: "Renault Kwid, Duster",
    rating: 4.3,
    reviews: 134,
    make: "Renault",
    model: "Kwid",
    year: "2023",
  },
  {
    id: "16",
    name: "Side Mirror Assembly",
    brand: "Fiem",
    category: "Body Parts",
    price: 1299,
    originalPrice: 1899,
    image: "https://images.unsplash.com/photo-1581092162080-8cda6b69a135?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 44,
    genuine: true,
    discount: 14,
    compatibility: "Volkswagen Polo, Vento",
    rating: 4.6,
    reviews: 201,
    make: "Volkswagen",
    model: "Polo",
    year: "2024",
  },
  {
    id: "17",
    name: "Windshield Wipers",
    brand: "Bosch",
    category: "Body Parts",
    price: 499,
    originalPrice: 699,
    image: "https://images.unsplash.com/photo-1581092162080-8cda6b69a136?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 78,
    genuine: true,
    discount: 28,
    compatibility: "All Cars",
    rating: 4.5,
    reviews: 512,
    make: "Maruti",
    model: "Baleno",
    year: "2024",
  },
  {
    id: "18",
    name: "Cabin Air Filter",
    brand: "Mann",
    category: "Filters",
    price: 399,
    originalPrice: 599,
    image: "https://images.unsplash.com/photo-1581092160562-40cb08bac843?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 68,
    genuine: true,
    discount: 33,
    compatibility: "All Cars",
    rating: 4.7,
    reviews: 298,
    make: "Hyundai",
    model: "Verna",
    year: "2023",
  },
  {
    id: "19",
    name: "Disc Brake Rotor",
    brand: "TRW",
    category: "Brakes",
    price: 899,
    originalPrice: 1299,
    image: "https://images.unsplash.com/photo-1581092150562-40cb08bac844?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 39,
    genuine: true,
    discount: 19,
    compatibility: "Tata Tigor, Harrier",
    rating: 4.8,
    reviews: 276,
    make: "Tata",
    model: "Tigor",
    year: "2024",
  },
  {
    id: "20",
    name: "Shock Absorber",
    brand: "KYB",
    category: "Suspension",
    price: 2499,
    originalPrice: 3699,
    image: "https://images.unsplash.com/photo-1581092162080-8cda6b69a137?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 25,
    genuine: true,
    discount: 24,
    compatibility: "Honda Amaze, City",
    rating: 4.7,
    reviews: 234,
    make: "Honda",
    model: "Amaze",
    year: "2023",
  },
  {
    id: "21",
    name: "Engine Oil Filter Pro",
    brand: "Mann",
    category: "Filters",
    price: 379,
    originalPrice: 549,
    image: "https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 38,
    genuine: true,
    discount: 13,
    compatibility: "Maruti Swift, Alto, Celerio",
    rating: 4.7,
    reviews: 198,
    make: "Maruti",
    model: "Swift",
    year: "2022",
  },
  {
    id: "22",
    name: "Air Filter Professional",
    brand: "Bosch",
    category: "Filters",
    price: 329,
    originalPrice: 499,
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 52,
    genuine: true,
    discount: 21,
    compatibility: "Maruti Swift, Alto, Celerio",
    rating: 4.8,
    reviews: 267,
    make: "Maruti",
    model: "Swift",
    year: "2021",
  },
  {
    id: "23",
    name: "Spark Plug Kit",
    brand: "NGK",
    category: "Engine Parts",
    price: 649,
    originalPrice: 999,
    image: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 41,
    genuine: true,
    discount: 17,
    compatibility: "Maruti Swift, Alto, Celerio",
    rating: 4.6,
    reviews: 289,
    make: "Maruti",
    model: "Swift",
    year: "2020",
  },
  {
    id: "24",
    name: "Battery Premium",
    brand: "Exide",
    category: "Electrical",
    price: 3999,
    originalPrice: 5299,
    image: "https://images.unsplash.com/photo-1581092934665-96e8bb648b0f?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 19,
    genuine: true,
    discount: 25,
    compatibility: "Maruti Swift, Alto, Celerio",
    rating: 4.8,
    reviews: 445,
    make: "Maruti",
    model: "Swift",
    year: "2019",
  },
  {
    id: "25",
    name: "Brake Pad Assembly",
    brand: "Brembo",
    category: "Brakes",
    price: 1199,
    originalPrice: 1699,
    image: "https://images.unsplash.com/photo-1516684657222-7d7d9c2eae5d?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 33,
    genuine: true,
    discount: 22,
    compatibility: "Maruti Swift, Alto, Celerio",
    rating: 4.9,
    reviews: 512,
    make: "Maruti",
    model: "Swift",
    year: "2024",
  },
  {
    id: "26",
    name: "Alternator Premium",
    brand: "Bosch",
    category: "Electrical",
    price: 5499,
    originalPrice: 7499,
    image: "https://images.unsplash.com/photo-1581092891221-8022df4466f9?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 15,
    genuine: true,
    discount: 26,
    compatibility: "Maruti Swift, Alto, Celerio",
    rating: 4.8,
    reviews: 302,
    make: "Maruti",
    model: "Swift",
    year: "2022",
  },
  {
    id: "27",
    name: "Water Pump Kit",
    brand: "Kirloskar",
    category: "Cooling",
    price: 2599,
    originalPrice: 3899,
    image: "https://images.unsplash.com/photo-1581092334473-e85ebef0edd4?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 11,
    genuine: true,
    discount: 33,
    compatibility: "Maruti Swift, Alto, Celerio",
    rating: 4.7,
    reviews: 178,
    make: "Maruti",
    model: "Swift",
    year: "2021",
  },
  {
    id: "28",
    name: "Suspension Spring Set",
    brand: "TRW",
    category: "Suspension",
    price: 1699,
    originalPrice: 2499,
    image: "https://images.unsplash.com/photo-1581092167562-40cb08bac841?w=400&h=400&fit=crop",
    inStock: true,
    stockCount: 28,
    genuine: true,
    discount: 19,
    compatibility: "Maruti Swift, Alto, Celerio",
    rating: 4.6,
    reviews: 201,
    make: "Maruti",
    model: "Swift",
    year: "2020",
  },
];
